inputs:
  database_url:
    description: "URL do banco de dados PostgreSQL"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: "Install UV"
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
      env:
        DATABASE_URL: ${{ inputs.database_url }}