runs:
  using: composite
  steps:
    - name: "Install UV"
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
      env:
        database_url: ${{ secrets.DATABASE_URL }}