table usuarios {
  id integer [primary key]
  nome varchar
  email varchar
  senha varchar
  funcao varchar
  biografia varchar
}

table links_redes {
  id integer [primary key]
  id_usuario integer [ref: > usuarios.id]
  link varchar
  nome_rede varchar
  nome_usuario varchar
}

table obras{
    id integer [primary key]
    id_categoria int [ref: > categorias.id]
    id_artista int [ref: > usuarios.id]
    titulo varchar
    body text
    status varchar
    data_postagem timestamp
    ano_producao timestamp
    tecnica_criacao varchar
    altura float
    largura float
    comprimento float
    peso float
    preco float
    tags varchar
}


table eventos{
  id int [primary key]
  id_organizador int [ref: > usuarios.id]
  id_responsavel int [ref: > usuarios.id]
  endereco varchar
  local varchar
  data datetime
}

table obra_evento{
  id_obra int [ref: > obras.id]
  id_evento int [ref: > eventos.id]
}

table usuario_evento{
  id_usuario int [ref: > usuarios.id]
  id_evento int [ref: > eventos.id]
}


table comentario_obras{
  id int [primary key]
  id_obra int [ref: > obras.id]
  id_usuario int [ref: > usuarios.id]
  ativado bool
}

table comentario_eventos{
  id int [primary key]
  id_evento int [ref: > eventos.id]
  id_usuario int [ref: > usuarios.id]
  texto varchar
  ativado bool
}

table avaliacoes_obras{
  id int [primary key]
  id_obra int [ref: > obras.id]
  id_usuario int [ref: > usuarios.id]
  gostou bool
  avaliacao int
}

table avaliacoes_eventos{
  id int [primary key]
  id_evento int [ref: > eventos.id]
  id_usuario int [ref: > usuarios.id]
  gostou bool
  avaliacao int
}

table categorias{
  id int [primary key]
  id_obra int [ref: > obras.id]
  nome varchar
}
