"""adição de texto na tabela ComentarioObra

Revision ID: 114629e2de17
Revises: f26aeed58b74
Create Date: 2025-10-02 21:11:18.761811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '114629e2de17'
down_revision: Union[str, Sequence[str], None] = 'f26aeed58b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentario_eventos',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('comentario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', 'PENDENTE', name='statuscomentario'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comentario_obras', sa.Column('texto', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('comentario_obras', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.add_column('comentario_obras', sa.Column('obra_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('comentario_obras_id_usuario_fkey'), 'comentario_obras', type_='foreignkey')
    op.drop_constraint(op.f('comentario_obras_id_obra_fkey'), 'comentario_obras', type_='foreignkey')
    op.create_foreign_key(None, 'comentario_obras', 'obras', ['obra_id'], ['id'])
    op.create_foreign_key(None, 'comentario_obras', 'usuarios', ['usuario_id'], ['id'])
    op.drop_column('comentario_obras', 'id_usuario')
    op.drop_column('comentario_obras', 'id_obra')
    op.drop_column('obras', 'id_artista')
    op.drop_column('obras', 'id_categoria')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obras', sa.Column('id_categoria', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('obras', sa.Column('id_artista', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('comentario_obras', sa.Column('id_obra', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('comentario_obras', sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comentario_obras', type_='foreignkey')
    op.drop_constraint(None, 'comentario_obras', type_='foreignkey')
    op.create_foreign_key(op.f('comentario_obras_id_obra_fkey'), 'comentario_obras', 'usuarios', ['id_obra'], ['id'])
    op.create_foreign_key(op.f('comentario_obras_id_usuario_fkey'), 'comentario_obras', 'usuarios', ['id_usuario'], ['id'])
    op.drop_column('comentario_obras', 'obra_id')
    op.drop_column('comentario_obras', 'usuario_id')
    op.drop_column('comentario_obras', 'texto')
    op.drop_table('comentario_eventos')
    # ### end Alembic commands ###
