"""Adição de coordenadas geográficas no evento

Revision ID: 1c5b605f4c0f
Revises: 2ef38f04ef3d
Create Date: 2025-11-23 14:24:11.450055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1c5b605f4c0f'
down_revision: Union[str, Sequence[str], None] = '2ef38f04ef3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventos', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('eventos', sa.Column('longitude', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventos', 'longitude')
    op.drop_column('eventos', 'latitude')
    # ### end Alembic commands ###
