"""Criação da Tabela Obras

Revision ID: 519941dbf98e
Revises: a92865ea64aa
Create Date: 2025-09-26 20:34:26.216076

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26cfa8a9b058"
down_revision: Union[str, Sequence[str], None] = "6596c0ca3538"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "obras",
        sa.Column("titulo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("autor", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ano_producao", sa.Integer(), nullable=False),
        sa.Column(
            "tecnica_criacao", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("altura_centimetros", sa.Float(), nullable=False),
        sa.Column("largura_centimetros", sa.Float(), nullable=False),
        sa.Column("peso_quilos", sa.Float(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("preco", sa.Float(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("data_postagem", sa.DateTime(), nullable=False),
        sa.Column("id_artista", sa.Integer(), nullable=False),
        sa.Column("id_categoria", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("categoria_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["categoria_id"],
            ["categorias.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("obras")
    # ### end Alembic commands ###
