"""Criação das tabelas de avaliações de eventos e associação obra-evento

Revision ID: 2ef38f04ef3d
Revises: 114629e2de17
Create Date: 2025-10-25 18:13:59.272233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2ef38f04ef3d'
down_revision: Union[str, Sequence[str], None] = '114629e2de17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comentario_obras', 'obras', ['obra_id'], ['id'])
    op.create_foreign_key(None, 'comentario_obras', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comentario_obras', type_='foreignkey')
    op.drop_constraint(None, 'comentario_obras', type_='foreignkey')
    # ### end Alembic commands ###
