"""Novos campos pro usuario

Revision ID: 4894c9d235da
Revises: 41590745c3be
Create Date: 2025-08-26 19:06:25.595034

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4894c9d235da"
down_revision: Union[str, Sequence[str], None] = "41590745c3be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Criar o tipo ENUM antes de usá-lo (necessário para PostgreSQL)
    funcao_enum = sa.Enum("CONSUMIDOR", "ARTISTA", "ADMIN", name="funcao")
    funcao_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "usuarios",
        sa.Column(
            "funcao",
            funcao_enum,
            nullable=False,
        ),
    )
    op.add_column(
        "usuarios",
        sa.Column("biografia", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usuarios", "biografia")
    op.drop_column("usuarios", "funcao")

    # Remover o tipo ENUM após remover a coluna (necessário para PostgreSQL)
    sa.Enum(name="funcao").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
