"""Novos campos pro usuario

Revision ID: 4894c9d235da
Revises: 41590745c3be
Create Date: 2025-08-26 19:06:25.595034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4894c9d235da'
down_revision: Union[str, Sequence[str], None] = '41590745c3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('funcao', sa.Enum('CONSUMIDOR', 'ARTISTA', 'ADMIN', name='funcao'), nullable=False))
    op.add_column('usuarios', sa.Column('biografia', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'biografia')
    op.drop_column('usuarios', 'funcao')
    # ### end Alembic commands ###
