"""create_link_rede_table

Revision ID: 5b681c3d5f50
Revises: 4894c9d235da
Create Date: 2025-09-03 19:02:54.298166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5b681c3d5f50'
down_revision: Union[str, Sequence[str], None] = '4894c9d235da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('funcao', sa.Enum('CONSUMIDOR', 'ARTISTA', 'ADMIN', name='funcao'), nullable=False),
    sa.Column('biografia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('senha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('link_redes',
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome_rede', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome_usuario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link_redes')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
