"""create_events_table

Revision ID: 6596c0ca3538
Revises: 4894c9d235da
Create Date: 2025-09-08 19:14:49.700027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6596c0ca3538'
down_revision: Union[str, Sequence[str], None] = '4894c9d235da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Eventos',
    sa.Column('endereco', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('local', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('id_organizador', sa.Integer(), nullable=False),
    sa.Column('id_responsavel', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_organizador'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_responsavel'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Eventos')
    # ### end Alembic commands ###
