"""remove campo senha e manter senha_hash no modelo UsuarioDB

Revision ID: 8a4d6370b844
Revises: 2ef38f04ef3d
Create Date: 2025-11-07 20:27:31.168735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8a4d6370b844'
down_revision: Union[str, Sequence[str], None] = '2ef38f04ef3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
