"""Criação da tabela Link Rede


Revision ID: a92865ea64aa
Revises: 197d97706f84
Create Date: 2025-09-11 21:59:11.137791

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a92865ea64aa"
down_revision: Union[str, Sequence[str], None] = "197d97706f84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "link_redes",
        sa.Column("link", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("nome_rede", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("nome_usuario", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id_usuario", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_usuario"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("link_redes")
    # ### end Alembic commands ###
