"""criação do modelo avaliação obra

Revision ID: de5b170dc9bb
Revises: 2ef38f04ef3d
Create Date: 2025-11-24 22:01:53.563246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'de5b170dc9bb'
down_revision: Union[str, Sequence[str], None] = '2ef38f04ef3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacoes_eventos',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('gostou', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avaliacao', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliacoes_obras',
    sa.Column('id_obra', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('gostou', sa.Boolean(), nullable=False),
    sa.Column('avaliacao', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_obra'], ['obras.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obra_evento',
    sa.Column('id_obra', sa.Integer(), nullable=False),
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_evento'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['id_obra'], ['obras.id'], ),
    sa.PrimaryKeyConstraint('id_obra', 'id_evento')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('obra_evento')
    op.drop_table('avaliacoes_obras')
    op.drop_table('avaliacoes_eventos')
    # ### end Alembic commands ###
