"""criação da tabela comentario_obras

Revision ID: f26aeed58b74
Revises: a92865ea64aa
Create Date: 2025-09-26 19:31:23.467216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f26aeed58b74'
down_revision: Union[str, Sequence[str], None] = 'a92865ea64aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentario_obras',
    sa.Column('ativado', sa.Boolean(), nullable=False),
    sa.Column('id_obra', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_obra'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentario_obras')
    # ### end Alembic commands ###
